### ISSUE TITLE
Tool-tip is shown while dragging genes, making it difficult to see where you want to drop the gene.

### ISSUE THREAD

**Issue by eliannelavoie** [pmotschmann/Evolve#645]
![difficultToSee](https://user-images.githubusercontent.com/13744678/141663556-50a3e835-8ef7-449a-b04e-76c0dba8e87f.gif)

The tool-tip is shown while you're dragging, so it hides what's underneath.

I think the rule:
```css
.sortable-chosen .tooltip-content {
  display: none;
}
```
fixes the problem well.

![easierToSee](https://user-images.githubusercontent.com/13744678/141663580-cb43db3d-ea57-4bc5-8cc2-f9827a0c4eed.gif)
